# Altera o tema
set colorscheme dracula

# Adiciona as linhas de divisão
# "separators" desenha apenas as linhas entre as janelas/colunas. 
# Mude para "both" se quiser uma borda externa completa.
set draw_borders separators

# Ativa o script scope.sh (para PDFs, Vídeos, Markdown)
set use_preview_script true

# Habilita o preview de imagens
set preview_images true

# Define o método de renderização para o ueberzugpp
set preview_images_method ueberzug

# Esconde arquivos que começam com ponto (e outros definidos no filtro)
set show_hidden false

# Garante que o tamanho será exibido na coluna principal
set display_size_in_main_column true

# Calcula o tamanho real dos diretórios automaticamente
set autoupdate_cumulative_size false
