# Options to make tmux more pleasant
set -g mouse on
set -g mode-keys vi
set -s set-clipboard on

# Switch panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 1. Define o atalho (Prefix + Ctrl-r) para entrar no modo "resize"
bind C-r switch-client -T resize

# 2. Mapeia h, j, k, l dentro do modo "resize" para redimensionar em 5 blocos
# O '\; switch-client -T resize' no final mantém você preso neste modo 
# para que possa apertar as teclas várias vezes seguidas (como no i3)
bind -T resize h resize-pane -L 5 \; switch-client -T resize
bind -T resize j resize-pane -D 5 \; switch-client -T resize
bind -T resize k resize-pane -U 5 \; switch-client -T resize
bind -T resize l resize-pane -R 5 \; switch-client -T resize

# 3. Define teclas para SAIR do modo resize (Esc ou Enter) e voltar ao normal
bind -T resize Escape switch-client -T root
bind -T resize Enter switch-client -T root

# don't rename windows automatically
set-option -g allow-rename off

# Reload
bind r source-file ~/.tmux.conf

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right '%Y-%m-%d %H:%M '
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

# messages
set -g message-style 'fg=yellow bg=red bold'

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"
set-option -g destroy-unattached on

